# file=Report.ini
#export path, please change to real path in your computer
#report.export.filepath=/Users/royeyu/Downloads/report.xls

# original file path
#report.original.filepath=/Users/royeyu/Downloads/yindaojing

file=Report.ini
#export path, please change to real path in your computer
report.export.filepath=E:\\desktop\\colposcopy\\report.xls

# original file path
report.original.filepath=G:\\colposcopy\\yindaojing